export const CIVIL_REGISTRY_SERVICES = [
	{ id: 1001, uz: { name: "Tug'ilganlik haqida guvohnoma olish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Получение свидетельства о рождении", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Birth Certificate Issuance", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Туу туралы куәлік алу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["tug'ilganlik", "guvohnoma", "birth certificate", "свидетельство рождения", "bola", "newborn", "chaqaloq", "register birth", "birth registration"] },
	{ id: 1002, uz: { name: "Nikohni qayd etish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Регистрация брака", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Marriage Registration", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Некені тіркеу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["nikoh", "marriage", "wedding", "брак", "свадьба", "marry", "wed", "turmush", "uylanish", "register marriage"] },
	{ id: 1003, uz: { name: "Ajralishni (ajrimni) qayd etish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Регистрация развода", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Divorce Registration", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Ажырасуды тіркеу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["ajralish", "ajrim", "divorce", "развод", "talaq", "separated", "разводиться"] },
	{ id: 1004, uz: { name: "O'lim haqida guvohnoma olish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Получение свидетельства о смерти", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Death Certificate", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Қайтыс болу туралы куәлік алу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["o'lim", "vafot", "death", "смерть", "умер", "died", "death certificate", "свидетельство смерти", "deceased"] },
	{ id: 1005, uz: { name: "Ism-familyani o'zgartirish", category: "Fuqarolik", org: "FHDY" }, ru: { name: "Изменение имени и фамилии", category: "Гражданство", org: "ЗАГС" }, en: { name: "Name/Surname Change", category: "Citizenship", org: "Civil Registry" }, kk: { name: "Аты-жөнін өзгерту", category: "Азаматтық", org: "АХАЖ" }, keywords: ["ism o'zgartirish", "familya", "name change", "фамилия", "имя", "смена имени", "new name", "surname change", "аты"] },
	{ id: 1006, uz: { name: "Fuqarolik holat aktlari yozuvlarida tuzatish kiritish", category: "Fuqarolik", org: "FHDY" }, ru: { name: "Внесение исправлений в записи актов гражданского состояния", category: "Гражданство", org: "ЗАГС" }, en: { name: "Civil Status Record Correction", category: "Citizenship", org: "Civil Registry" }, kk: { name: "Азаматтық хал актілері жазбаларына түзетулер", category: "Азаматтық", org: "АХАЖ" }, keywords: ["tuzatish", "record correction", "исправление записи", "ЗАГС тузатиш", "typo correction", "civil record fix", "birth record error"] },
	{ id: 1007, uz: { name: "Nikoh guvohnomasining dublikatini olish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Получение дубликата свидетельства о браке", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Duplicate Marriage Certificate", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Некеге тіркеу куәлігінің дубликатын алу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["nikoh dublikat", "marriage certificate copy", "дубликат свидетельства брак", "lost marriage certificate", "replace marriage cert"] },
	{ id: 1008, uz: { name: "Tug'ilganlik guvohnomasining dublikatini olish", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Получение дубликата свидетельства о рождении", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Duplicate Birth Certificate", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Туу куәлігінің дубликатын алу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["tug'ilganlik dublikat", "birth certificate copy", "дубликат свидетельства рождения", "lost birth certificate", "replace birth cert"] },
	{ id: 1009, uz: { name: "Vasiylik va homiylikni rasmiylashtirish", category: "Oila va bolalar", org: "Mahalla va oila vazirligi" }, ru: { name: "Оформление опеки и попечительства", category: "Семья и дети", org: "Министерство семьи" }, en: { name: "Guardianship and Trusteeship", category: "Family and Children", org: "Ministry of Family" }, kk: { name: "Қорғаншылық және қамқорлықты ресімдеу", category: "Отбасы және балалар", org: "Отбасы министрлігі" }, keywords: ["vasiylik", "homiylik", "guardian", "опека", "попечительство", "orphan", "yetim", "adoption", "усыновление", "farzandlikka olish"] },
	{ id: 1010, uz: { name: "Farzandlikka olish (udochered qilish / bola qabul qilish)", category: "Oila va bolalar", org: "Mahalla va oila vazirligi" }, ru: { name: "Усыновление (удочерение) ребёнка", category: "Семья и дети", org: "Министерство семьи" }, en: { name: "Child Adoption", category: "Family and Children", org: "Ministry of Family" }, kk: { name: "Бала асырап алу", category: "Отбасы және балалар", org: "Отбасы министрлігі" }, keywords: ["farzandlikka olish", "adoption", "усыновление", "bola qabul", "adopt child", "adoptive parent", "fostecare", "foster child"] },
	{ id: 1011, uz: { name: "Bolani otasini aniqlash (otaliklarni o'rnatish)", category: "Oila va bolalar", org: "FHDY" }, ru: { name: "Установление отцовства", category: "Семья и дети", org: "ЗАГС" }, en: { name: "Paternity Establishment", category: "Family and Children", org: "Civil Registry" }, kk: { name: "Әкелікті белгілеу", category: "Отбасы және балалар", org: "АХАЖ" }, keywords: ["otalik", "paternity", "отцовство", "установить отца", "father recognition", "bola otasi", "DNA", "патернити"] },
	{ id: 1012, uz: { name: "Ko'p bolali oilalarga yordam dasturlarini rasmiylashtirish", category: "Oila va bolalar", org: "Mahalla va oila vazirligi" }, ru: { name: "Оформление программ поддержки многодетных семей", category: "Семья и дети", org: "Министерство семьи" }, en: { name: "Large Family Support Programmes", category: "Family and Children", org: "Ministry of Family" }, kk: { name: "Көп балалы отбасыларға қолдау бағдарламалары", category: "Отбасы және балалар", org: "Отбасы министрлігі" }, keywords: ["ko'p bolali", "many children", "многодетная", "large family benefit", "family support", "ko'p farzand", "mother allowance"] },
];