export const CONSTRUCTION_SERVICES = [
	{ id: 1701, uz: { name: "Uy-joy qurilishiga ruxsatnoma olish", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Разрешение на строительство жилья", category: "Строительство", org: "Министерство строительства" }, en: { name: "Residential Building Permit", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Тұрғын үй құрылысына рұқсат", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["qurilish ruxsat", "building permit", "строить", "разрешение", "стройка", "uy qurish", "build house", "construction permit", "yangi uy"] },
	{ id: 1702, uz: { name: "Tijorat ob'ekt qurilishiga ruxsatnoma", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Разрешение на строительство коммерческого объекта", category: "Строительство", org: "Министерство строительства" }, en: { name: "Commercial Building Permit", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Коммерциялық нысан құрылысына рұқсат", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["tijorat qurilish", "commercial building", "магазин строить", "офис", "office build", "store build", "commercial construction"] },
	{ id: 1703, uz: { name: "Binoni foydalanishga topshirish akti", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Акт ввода здания в эксплуатацию", category: "Строительство", org: "Министерство строительства" }, en: { name: "Building Completion and Handover Certificate", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Ғимаратты пайдалануға беру актісі", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["topshirish akti", "completion certificate", "ввод в эксплуатацию", "qurilish tugash", "finished building", "building handover"] },
	{ id: 1704, uz: { name: "Arxitektura-rejalashtirish topshirig'i olish", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Получение архитектурно-планировочного задания", category: "Строительство", org: "Министерство строительства" }, en: { name: "Architectural Planning Assignment", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Архитектуралық-жоспарлау тапсырмасын алу", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["arxitektura", "architectural planning", "архитектурное задание", "design plan", "loyiha", "project design", "building project"] },
	{ id: 1705, uz: { name: "Binoni rekonstruksiya qilishga ruxsatnoma", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Разрешение на реконструкцию здания", category: "Строительство", org: "Министерство строительства" }, en: { name: "Building Reconstruction Permit", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Ғимаратты қайта жөндеуге рұқсат", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["rekonstruksiya", "reconstruction", "renovation permit", "rebuild", "реконструкция", "renovation", "bino qayta qurish"] },
	{ id: 1706, uz: { name: "Yer uchastkasiga qurilish dizayni tasdiqlash", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Утверждение проекта строительства на участке", category: "Строительство", org: "Министерство строительства" }, en: { name: "Site Construction Design Approval", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Учаскедегі құрылыс жобасын бекіту", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["dizayn tasdiqlash", "design approval", "проект утверждение", "building design", "site plan", "loyiha tasdiqlash"] },
	{ id: 1707, uz: { name: "Qurilish materiallari sifatini sertifikatlashtirish", category: "Qurilish", org: "Qurilish vazirligi" }, ru: { name: "Сертификация качества строительных материалов", category: "Строительство", org: "Министерство строительства" }, en: { name: "Construction Materials Quality Certification", category: "Construction", org: "Ministry of Construction" }, kk: { name: "Құрылыс материалдары сапасын сертификаттау", category: "Құрылыс", org: "Құрылыс министрлігі" }, keywords: ["qurilish material", "construction material", "цемент", "кирпич", "building materials certificate", "material quality", "sement"] },
	{ id: 1708, uz: { name: "Yong'in xavfsizligi sertifikati olish", category: "Qurilish", org: "FVV" }, ru: { name: "Получение сертификата пожарной безопасности", category: "Строительство", org: "МЧС" }, en: { name: "Fire Safety Certificate", category: "Construction", org: "Emergency Situations Ministry" }, kk: { name: "Өрт қауіпсіздігі сертификатын алу", category: "Құрылыс", org: "ТЖМ" }, keywords: ["yong'in", "xavfsizlik", "fire safety", "пожар", "МЧС", "fire certificate", "sprinkler", "fire inspection", "fire permit"] },
];

export const REAL_ESTATE_SERVICES = [
	{ id: 1801, uz: { name: "Kvartira yoki uy sotib olish-sotish shartnomasi ro'yxatdan o'tkazish", category: "Ko'chmas mulk", org: "Kadastr agentligi" }, ru: { name: "Регистрация договора купли-продажи квартиры/дома", category: "Недвижимость", org: "Кадастр" }, en: { name: "Property Sale/Purchase Agreement Registration", category: "Real Estate", org: "Cadastre Agency" }, kk: { name: "Пәтер/үй сатып алу-сату шартын тіркеу", category: "Жылжымайтын мүлік", org: "Кадастр агенттігі" }, keywords: ["kvartira sotish", "uy sotish", "property sale", "купля-продажа", "buy apartment", "uy sotib olish", "property contract"] },
	{ id: 1802, uz: { name: "Ipoteka kreditiga davlat subsidiyasi", category: "Ko'chmas mulk", org: "Iqtisodiyot vazirligi" }, ru: { name: "Государственная субсидия на ипотеку", category: "Недвижимость", org: "Минэкономики" }, en: { name: "Mortgage State Subsidy", category: "Real Estate", org: "Ministry of Economy" }, kk: { name: "Ипотекаға мемлекеттік субсидия", category: "Жылжымайтын мүлік", org: "Экономика министрлігі" }, keywords: ["ipoteka", "mortgage", "ипотека", "subsidiya", "housing loan", "arzon uy", "cheap house", "льготный кредит"] },
	{ id: 1803, uz: { name: "Uy-joy ijarasini ro'yxatdan o'tkazish", category: "Ko'chmas mulk", org: "Soliq qo'mitasi" }, ru: { name: "Регистрация договора аренды жилья", category: "Недвижимость", org: "Налоговый комитет" }, en: { name: "Rental Agreement Registration", category: "Real Estate", org: "Tax Committee" }, kk: { name: "Тұрғын үй жалдау шартын тіркеу", category: "Жылжымайтын мүлік", org: "Салық комитеті" }, keywords: ["ijara", "rent", "квартира аренда", "rental contract", "lease", "ijaraga berish", "ijaraga olish", "rent apartment"] },
	{ id: 1804, uz: { name: "Ko'chmas mulkni garovga qo'yish", category: "Ko'chmas mulk", org: "Kadastr agentligi" }, ru: { name: "Залог недвижимого имущества", category: "Недвижимость", org: "Кадастр" }, en: { name: "Real Estate as Collateral/Pledge", category: "Real Estate", org: "Cadastre Agency" }, kk: { name: "Жылжымайтын мүлікті кепілге беру", category: "Жылжымайтын мүлік", org: "Кадастр агенттігі" }, keywords: ["garov", "pledge", "collateral", "залог", "mortgage collateral", "uy garov", "property pledge", "bank garov"] },
	{ id: 1805, uz: { name: "Uy-joy bepul ta'minlash (ijtimoiy maqsadli)", category: "Ko'chmas mulk", org: "Qurilish vazirligi" }, ru: { name: "Бесплатное предоставление жилья (социальное)", category: "Недвижимость", org: "Министерство строительства" }, en: { name: "Free Social Housing Provision", category: "Real Estate", org: "Ministry of Construction" }, kk: { name: "Тегін тұрғын үй беру (әлеуметтік)", category: "Жылжымайтын мүлік", org: "Құрылыс министрлігі" }, keywords: ["bepul uy", "social housing", "free housing", "государственное жильё", "davlat uy", "subsidized home", "social home"] },
	{ id: 1806, uz: { name: "Ko'chmas mulkni baholash (ekspertiza)", category: "Ko'chmas mulk", org: "Kadastr agentligi" }, ru: { name: "Оценка (экспертиза) недвижимости", category: "Недвижимость", org: "Кадастр" }, en: { name: "Real Estate Valuation/Appraisal", category: "Real Estate", org: "Cadastre Agency" }, kk: { name: "Жылжымайтын мүлікті бағалау", category: "Жылжымайтын мүлік", org: "Кадастр агенттігі" }, keywords: ["baholash", "valuation", "appraisal", "оценка", "mulk narxi", "property value", "real estate price"] },
];