export const CONSUMER_SERVICES = [
	{ id: 2101, uz: { name: "Iste'molchi huquqlarini himoya qilish shikoyati", category: "Iste'molchilar himoyasi", org: "Antimonopol qo'mita" }, ru: { name: "Жалоба на защиту прав потребителей", category: "Защита потребителей", org: "Антимонопольный комитет" }, en: { name: "Consumer Rights Protection Complaint", category: "Consumer Protection", org: "Anti-Monopoly Committee" }, kk: { name: "Тұтынушы құқықтарын қорғауға шағым", category: "Тұтынушыларды қорғау", org: "Монополияға қарсы комитет" }, keywords: ["iste'molchi", "consumer", "protection", "rights", "shikoyat", "права потребителя", "жалоба", "refund", "tovar qaytarish", "seller fraud", "aldov"] },
	{ id: 2102, uz: { name: "Tovar sifati nazorati va shikoyat", category: "Iste'molchilar himoyasi", org: "Antimonopol qo'mita" }, ru: { name: "Контроль качества товара и жалоба", category: "Защита потребителей", org: "Антимонопольный комитет" }, en: { name: "Product Quality Control and Complaint", category: "Consumer Protection", org: "Anti-Monopoly Committee" }, kk: { name: "Тауар сапасын бақылау және шағым", category: "Тұтынушыларды қорғау", org: "Монополияға қарсы комитет" }, keywords: ["sifat shikoyat", "quality complaint", "некачественный товар", "product defect", "bad product", "defective", "sifatsiz mahsulot"] },
	{ id: 2103, uz: { name: "Oziq-ovqat xavfsizligi nazorati", category: "Iste'molchilar himoyasi", org: "Sanitariya epidemiologiya xizmati" }, ru: { name: "Контроль безопасности пищевых продуктов", category: "Защита потребителей", org: "Санэпидслужба" }, en: { name: "Food Safety Control", category: "Consumer Protection", org: "Sanitary Epidemiological Service" }, kk: { name: "Тамақ өнімдерінің қауіпсіздігін бақылау", category: "Тұтынушыларды қорғау", org: "Санитарлық эпидемиологиялық қызмет" }, keywords: ["oziq-ovqat", "food safety", "пищевая безопасность", "food control", "sanitariya", "restaurant complaint", "bad food", "restoran shikoyat"] },
	{ id: 2104, uz: { name: "Antimonopol qo'mitaga ariza berish", category: "Iste'molchilar himoyasi", org: "Antimonopol qo'mita" }, ru: { name: "Обращение в антимонопольный комитет", category: "Защита потребителей", org: "Антимонопольный комитет" }, en: { name: "Anti-Monopoly Committee Complaint", category: "Consumer Protection", org: "Anti-Monopoly Committee" }, kk: { name: "Монополияға қарсы комитетке өтініш", category: "Тұтынушыларды қорғау", org: "Монополияға қарсы комитет" }, keywords: ["antimonopol", "monopoly", "антимонопольный", "competition violation", "price fixing", "narx monopoly", "market abuse"] },
	{ id: 2105, uz: { name: "Narxlarni tartibga solish shikoyati", category: "Iste'molchilar himoyasi", org: "Antimonopol qo'mita" }, ru: { name: "Жалоба на регулирование цен", category: "Защита потребителей", org: "Антимонопольный комитет" }, en: { name: "Price Regulation Complaint", category: "Consumer Protection", org: "Anti-Monopoly Committee" }, kk: { name: "Баға реттеуге шағым", category: "Тұтынушыларды қорғау", org: "Монополияға қарсы комитет" }, keywords: ["narx tartibga", "price control", "overpriced", "too expensive", "qimmat", "price gouging", "narx oshirib yubordi"] },
];

export const FOREIGN_AFFAIRS_SERVICES = [
	{ id: 2201, uz: { name: "Chet eldagi o'zbeklar uchun konsullik xizmati", category: "Tashqi ishlar", org: "Tashqi ishlar vazirligi" }, ru: { name: "Консульские услуги для граждан за рубежом", category: "Внешние дела", org: "МИД" }, en: { name: "Consular Services for Uzbeks Abroad", category: "Foreign Affairs", org: "Ministry of Foreign Affairs" }, kk: { name: "Шетелдегі өзбекстандықтарға консулдық қызмет", category: "Сыртқы істер", org: "СІМ" }, keywords: ["konsulat", "consulate", "embassy", "elchixona", "abroad", "chet el", "xorij", "konsullik", "diplomatic service", "overseas uzbek"] },
	{ id: 2202, uz: { name: "Apostil qo'yish va xorijda hujjatni legalizatsiya qilish", category: "Tashqi ishlar", org: "Adliya vazirligi" }, ru: { name: "Апостиль и легализация документов за рубежом", category: "Внешние дела", org: "Министерство юстиции" }, en: { name: "Apostille and Document Legalisation", category: "Foreign Affairs", org: "Ministry of Justice" }, kk: { name: "Апостиль және шетелде құжаттарды заңдастыру", category: "Сыртқы істер", org: "Әділет министрлігі" }, keywords: ["apostil", "apostille", "legalization", "notarial abroad", "document abroad", "xorijda hujjat", "international document"] },
	{ id: 2203, uz: { name: "Chet el fuqarolarini Uzbekistonga taklif qilish uchun ruxsatnoma", category: "Tashqi ishlar", org: "Tashqi ishlar vazirligi" }, ru: { name: "Разрешение на приглашение иностранных граждан в Узбекистан", category: "Внешние дела", org: "МИД" }, en: { name: "Invitation Permission for Foreign Citizens", category: "Foreign Affairs", org: "Ministry of Foreign Affairs" }, kk: { name: "Шетел азаматтарын шақыруға рұқсат", category: "Сыртқы істер", org: "СІМ" }, keywords: ["taklif", "invite foreigner", "invitation letter", "inviting", "приглашение иностранного", "visa invitation", "tourist invitation", "business invitation"] },
	{ id: 2204, uz: { name: "Xorijiy diplomlar va malakalarni tan olish", category: "Tashqi ishlar", org: "Oliy ta'lim vazirligi" }, ru: { name: "Признание иностранных дипломов и квалификаций", category: "Внешние дела", org: "Министерство высшего образования" }, en: { name: "Foreign Diploma and Qualification Recognition", category: "Foreign Affairs", org: "Ministry of Higher Education" }, kk: { name: "Шетелдік дипломдар мен біліктіліктерді тану", category: "Сыртқы істер", org: "Жоғары білім министрлігі" }, keywords: ["xorijiy diplom", "foreign diploma", "nostrifikatsiya", "diploma recognition", "recognize degree", "international degree", "degree abroad"] },
	{ id: 2205, uz: { name: "Chet el investitsiyalari uchun maxsus imtiyozlar", category: "Tashqi ishlar", org: "Investitsiyalar vazirligi" }, ru: { name: "Специальные льготы для иностранных инвесторов", category: "Внешние дела", org: "Министерство инвестиций" }, en: { name: "Special Benefits for Foreign Investors", category: "Foreign Affairs", org: "Ministry of Investment" }, kk: { name: "Шетелдік инвесторларға арнайы жеңілдіктер", category: "Сыртқы істер", org: "Инвестиция министрлігі" }, keywords: ["xorijiy investor", "foreign investor", "investment benefit", "инвестиции", "FDI", "foreign direct investment", "льготы инвестор"] },
];

export const ANTICORRUPTION_SERVICES = [
	{ id: 2301, uz: { name: "Korrupsiya faktlari haqida xabar berish", category: "Shikoyat va nazorat", org: "Antikorrupsiya agentligi" }, ru: { name: "Сообщение о фактах коррупции", category: "Жалобы и контроль", org: "Агентство по борьбе с коррупцией" }, en: { name: "Report Corruption", category: "Complaints and Oversight", org: "Anti-Corruption Agency" }, kk: { name: "Сыбайлас жемқорлық туралы хабарлау", category: "Шағымдар және бақылау", org: "Сыбайлас жемқорлыққа қарсы агенттік" }, keywords: ["korrupsiya", "pora", "bribe", "corruption", "report", "взятка", "коррупция", "anti corruption", "illegal", "noqonuniy", "hotline", "report abuse"] },
	{ id: 2302, uz: { name: "Davlat organlari faoliyatiga shikoyat (Ombudsman)", category: "Shikoyat va nazorat", org: "Ombudsman" }, ru: { name: "Жалоба на действия госорганов (Омбудсман)", category: "Жалобы и контроль", org: "Омбудсман" }, en: { name: "Complaint to Ombudsman (Against Government)", category: "Complaints and Oversight", org: "Ombudsman" }, kk: { name: "Мемлекеттік органдар іс-әрекеттеріне шағым (Омбудсман)", category: "Шағымдар және бақылау", org: "Омбудсман" }, keywords: ["ombudsman", "shikoyat", "жалоба омбудсман", "government complaint", "police complaint", "government abuse", "official misconduct"] },
	{ id: 2303, uz: { name: "Mulkiy manfaatlar deklaratsiyasini topshirish (mansabdorlar)", category: "Shikoyat va nazorat", org: "Antikorrupsiya agentligi" }, ru: { name: "Подача декларации об имущественных интересах (должностные лица)", category: "Жалобы и контроль", org: "Агентство по борьбе с коррупцией" }, en: { name: "Asset Declaration Filing (Officials)", category: "Complaints and Oversight", org: "Anti-Corruption Agency" }, kk: { name: "Мүліктік мүдделер декларациясын тапсыру (лауазымды тұлғалар)", category: "Шағымдар және бақылау", org: "Сыбайлас жемқорлыққа қарсы агенттік" }, keywords: ["deklaratsiya mulk", "asset declaration", "имущественная декларация", "declaration official", "government official", "официальный декларация"] },
];