export const CULTURE_SPORT_SERVICES = [
	{ id: 1901, uz: { name: "Madaniy tadbirlar o'tkazishga ruxsatnoma", category: "Madaniyat va turizm", org: "Madaniyat vazirligi" }, ru: { name: "Разрешение на проведение культурных мероприятий", category: "Культура и туризм", org: "Министерство культуры" }, en: { name: "Cultural Event Permit", category: "Culture and Tourism", org: "Ministry of Culture" }, kk: { name: "Мәдени іс-шараларға рұқсат", category: "Мәдениет және туризм", org: "Мәдениет министрлігі" }, keywords: ["madaniy tadbir", "cultural event", "концерт", "festival", "concert permit", "event permit", "tadbir ruxsat", "show permit"] },
	{ id: 1902, uz: { name: "Turizm agentligini ro'yxatdan o'tkazish", category: "Madaniyat va turizm", org: "Turizm agentligi" }, ru: { name: "Регистрация туристического агентства", category: "Культура и туризм", org: "Агентство туризма" }, en: { name: "Tourism Agency Registration", category: "Culture and Tourism", org: "Tourism Agency" }, kk: { name: "Туристік агенттікті тіркеу", category: "Мәдениет және туризм", org: "Туризм агенттігі" }, keywords: ["turizm agentlik", "tourism agency", "travel agency", "tour operator", "туристическое агентство", "sayyoh agentlik"] },
	{ id: 1903, uz: { name: "Mehmonxona va turistik ob'ekt ro'yxatdan o'tkazish", category: "Madaniyat va turizm", org: "Turizm agentligi" }, ru: { name: "Регистрация гостиницы и туристического объекта", category: "Культура и туризм", org: "Агентство туризма" }, en: { name: "Hotel and Tourism Object Registration", category: "Culture and Tourism", org: "Tourism Agency" }, kk: { name: "Қонақ үй мен туристік нысанды тіркеу", category: "Мәдениет және туризм", org: "Туризм агенттігі" }, keywords: ["mehmonxona", "hotel", "гостиница", "registration hotel", "tourism facility", "отель", "hostel", "guest house"] },
	{ id: 1904, uz: { name: "Sport musobaqasi o'tkazishga ruxsatnoma", category: "Sport va jismoniy tarbiya", org: "Sport agentligi" }, ru: { name: "Разрешение на проведение спортивных соревнований", category: "Спорт и физкультура", org: "Агентство спорта" }, en: { name: "Sports Competition Permit", category: "Sports and Physical Education", org: "Sports Agency" }, kk: { name: "Спорт жарыстарын өткізуге рұқсат", category: "Спорт және дене тәрбиесі", org: "Спорт агенттігі" }, keywords: ["sport musobaqa", "sports competition", "спортивное соревнование", "tournament permit", "sport event", "marakon", "marathon", "football tournament"] },
	{ id: 1905, uz: { name: "Sportchi litsenziyasini olish", category: "Sport va jismoniy tarbiya", org: "Sport agentligi" }, ru: { name: "Получение спортивной лицензии", category: "Спорт и физкультура", org: "Агентство спорта" }, en: { name: "Sports Licence", category: "Sports and Physical Education", org: "Sports Agency" }, kk: { name: "Спорт лицензиясын алу", category: "Спорт және дене тәрбиесі", org: "Спорт агенттігі" }, keywords: ["sportchi litsenziya", "sport license", "спортивная лицензия", "athlete license", "federation license", "professional sport"] },
	{ id: 1906, uz: { name: "Milliy meros ob'ektlarida tadbirlar uchun ruxsat", category: "Madaniyat va turizm", org: "Madaniyat vazirligi" }, ru: { name: "Разрешение на мероприятие в объектах наследия", category: "Культура и туризм", org: "Министерство культуры" }, en: { name: "Heritage Site Event Permit", category: "Culture and Tourism", org: "Ministry of Culture" }, kk: { name: "Мұра нысандарында іс-шараға рұқсат", category: "Мәдениет және туризм", org: "Мәдениет министрлігі" }, keywords: ["meros", "heritage", "Samarkand", "Bukhara", "Khiva", "Registan", "historical site", "event heritage", "мавзолей", "мечеть"] },
	{ id: 1907, uz: { name: "Kinematografiya va media litsenziyasi", category: "Madaniyat va turizm", org: "Madaniyat vazirligi" }, ru: { name: "Лицензия кинематографии и медиа", category: "Культура и туризм", org: "Министерство культуры" }, en: { name: "Cinematography and Media License", category: "Culture and Tourism", org: "Ministry of Culture" }, kk: { name: "Кинематография мен медиа лицензиясы", category: "Мәдениет және туризм", org: "Мәдениет министрлігі" }, keywords: ["kino", "cinema", "media", "film", "лицензия кино", "media license", "production license", "broadcast", "TV production"] },
	{ id: 1908, uz: { name: "Yoshlar dasturlari va grantlari", category: "Yoshlar", org: "Yoshlar ishlari agentligi" }, ru: { name: "Молодёжные программы и гранты", category: "Молодёжь", org: "Агентство по делам молодёжи" }, en: { name: "Youth Programmes and Grants", category: "Youth", org: "Youth Affairs Agency" }, kk: { name: "Жастар бағдарламалары мен гранттары", category: "Жастар", org: "Жастар істері агенттігі" }, keywords: ["yosh", "yoshlar", "youth program", "grant yoshlar", "young entrepreneur", "молодёжь программа", "startup youth", "grant yosh", "fellowship"] },
	{ id: 1909, uz: { name: "Xalqaro madaniy almashinuv dasturlari", category: "Madaniyat va turizm", org: "Tashqi ishlar vazirligi" }, ru: { name: "Международные программы культурного обмена", category: "Культура и туризм", org: "МИД" }, en: { name: "International Cultural Exchange Programmes", category: "Culture and Tourism", org: "Ministry of Foreign Affairs" }, kk: { name: "Халықаралық мәдени алмасу бағдарламалары", category: "Мәдениет және туризм", org: "СІМ" }, keywords: ["madaniy almashinuv", "cultural exchange", "xalqaro dastur", "international program", "diplomacy culture", "twinning"] },
];

export const RELIGION_MILITARY_SERVICES = [
	{ id: 2001, uz: { name: "Diniy tashkilotni ro'yxatdan o'tkazish", category: "Din ishlari", org: "Din ishlari qo'mitasi" }, ru: { name: "Регистрация религиозной организации", category: "Религиозные дела", org: "Комитет по делам религий" }, en: { name: "Religious Organisation Registration", category: "Religious Affairs", org: "Committee for Religious Affairs" }, kk: { name: "Діни ұйымды тіркеу", category: "Дін істері", org: "Дін істері жөніндегі комитет" }, keywords: ["diniy tashkilot", "masjid", "cherkov", "din", "religion", "mosque", "church", "register religion", "diniy ro'yxat", "ruhoniy"] },
	{ id: 2002, uz: { name: "Haj va umra sayohatiga ro'yxat", category: "Din ishlari", org: "Din ishlari qo'mitasi" }, ru: { name: "Регистрация на хадж или умру", category: "Религиозные дела", org: "Комитет по делам религий" }, en: { name: "Hajj and Umrah Registration", category: "Religious Affairs", org: "Committee for Religious Affairs" }, kk: { name: "Қажылыққа және умраға тіркелу", category: "Дін істері", org: "Дін істері жөніндегі комитет" }, keywords: ["haj", "umra", "mecca", "makka", "hajj", "pilgrimage", "ziyorat", "паломничество", "хадж", "умра", "register hajj"] },
	{ id: 2003, uz: { name: "Harbiy xizmatga chaqiriq ro'yxatga olish", category: "Mudofaa", org: "Mudofaa vazirligi" }, ru: { name: "Регистрация призыва на военную службу", category: "Оборона", org: "Министерство обороны" }, en: { name: "Military Conscription Registration", category: "Defence", org: "Ministry of Defence" }, kk: { name: "Әскери шақыруды тіркеу", category: "Қорғаныс", org: "Қорғаныс министрлігі" }, keywords: ["harbiy", "armiya", "askarga", "military", "conscription", "армия", "призыв", "army service", "harb xizmat"] },
	{ id: 2004, uz: { name: "Harbiy guvohnoma olish", category: "Mudofaa", org: "Mudofaa vazirligi" }, ru: { name: "Получение военного билета", category: "Оборона", org: "Министерство обороны" }, en: { name: "Military ID Card", category: "Defence", org: "Ministry of Defence" }, kk: { name: "Әскери куәлік алу", category: "Қорғаныс", org: "Қорғаныс министрлігі" }, keywords: ["harbiy guvohnoma", "military ID", "военный билет", "soldier ID", "army card", "military document", "voennik"] },
	{ id: 2005, uz: { name: "Harbiy xizmatdan kechiktirish yoki ozod qilish", category: "Mudofaa", org: "Mudofaa vazirligi" }, ru: { name: "Отсрочка или освобождение от военной службы", category: "Оборона", org: "Министерство обороны" }, en: { name: "Military Deferment or Exemption", category: "Defence", org: "Ministry of Defence" }, kk: { name: "Әскери қызметтен кейінге қалдыру немесе босату", category: "Қорғаныс", org: "Қорғаныс министрлігі" }, keywords: ["harbiy kechiktirish", "military deferment", "отсрочка армия", "exempt military", "student deferment", "o'qish kechiktirish", "medical exemption"] },
];