export const ENVIRONMENT_SERVICES = [
	{ id: 1301, uz: { name: "Ekologik ruxsatnoma (korxonalar uchun)", category: "Ekologiya", org: "Ekologiya agentligi" }, ru: { name: "Экологическое разрешение (для предприятий)", category: "Экология", org: "Агентство экологии" }, en: { name: "Environmental Permit (Business)", category: "Ecology", org: "Ecology Agency" }, kk: { name: "Экологиялық рұқсатнама (кәсіпорындар үшін)", category: "Экология", org: "Экология агенттігі" }, keywords: ["ekologik ruxsat", "environmental permit", "ecology permit", "pollution permit", "factory emission", "zavod", "chiqindi", "waste permit"] },
	{ id: 1302, uz: { name: "Suv resurslari ishlatish ruxsati", category: "Ekologiya", org: "Suv xo'jaligi vazirligi" }, ru: { name: "Разрешение на использование водных ресурсов", category: "Экология", org: "Министерство водного хозяйства" }, en: { name: "Water Resources Usage Permit", category: "Ecology", org: "Ministry of Water Resources" }, kk: { name: "Су ресурстарын пайдалануға рұқсат", category: "Экология", org: "Су шаруашылығы министрлігі" }, keywords: ["suv ruxsat", "water permit", "водные ресурсы", "irrigation", "sug'orish", "river use", "water extraction"] },
	{ id: 1303, uz: { name: "Chiqindilar boshqarish litsenziyasi", category: "Ekologiya", org: "Ekologiya agentligi" }, ru: { name: "Лицензия на управление отходами", category: "Экология", org: "Агентство экологии" }, en: { name: "Waste Management License", category: "Ecology", org: "Ecology Agency" }, kk: { name: "Қалдықтарды басқару лицензиясы", category: "Экология", org: "Экология агенттігі" }, keywords: ["chiqindi", "waste management", "утилизация", "мусор", "landfill", "отходы", "recycling", "waste license", "axlat"] },
	{ id: 1304, uz: { name: "Ko'k maydon va bog'larni loyihalash ruxsati", category: "Ekologiya", org: "Ekologiya agentligi" }, ru: { name: "Разрешение на проектирование зелёных зон и парков", category: "Экология", org: "Агентство экологии" }, en: { name: "Green Zone and Park Design Permit", category: "Ecology", org: "Ecology Agency" }, kk: { name: "Жасыл аймақтар мен парктерді жобалауға рұқсат", category: "Экология", org: "Экология агенттігі" }, keywords: ["ko'k maydon", "park", "green space", "bog' loyiha", "parkovaya zona", "landscape permit", "parks design"] },
	{ id: 1305, uz: { name: "Tuproq ifloslanishini bartaraf etish dasturi", category: "Ekologiya", org: "Ekologiya agentligi" }, ru: { name: "Программа по ликвидации загрязнения почвы", category: "Экология", org: "Агентство экологии" }, en: { name: "Soil Contamination Remediation", category: "Ecology", org: "Ecology Agency" }, kk: { name: "Топырақ ластануын жою бағдарламасы", category: "Экология", org: "Экология агенттігі" }, keywords: ["tuproq", "soil", "contamination", "pollution", "tozalash", "remediation", "environmental cleanup"] },
	{ id: 1306, uz: { name: "Atmosfera havosiga chiqarilgan zararli moddalar normasini belgilash", category: "Ekologiya", org: "Ekologiya agentligi" }, ru: { name: "Установление нормы выбросов вредных веществ в атмосферу", category: "Экология", org: "Агентство экологии" }, en: { name: "Air Pollution Emission Standards Setting", category: "Ecology", org: "Ecology Agency" }, kk: { name: "Атмосфераға зиянды заттар шығарындыларының нормасын белгілеу", category: "Экология", org: "Экология агенттігі" }, keywords: ["atmosfera", "emission standards", "air pollution", "havo ifloslanish", "сбросы", "выбросы", "air quality"] },
];

export const AGRICULTURE_SERVICES = [
	{ id: 1401, uz: { name: "Fermer xo'jaligini ro'yxatdan o'tkazish", category: "Qishloq xo'jaligi", org: "Qishloq xo'jaligi vazirligi" }, ru: { name: "Регистрация фермерского хозяйства", category: "Сельское хозяйство", org: "Министерство сельского хозяйства" }, en: { name: "Farm Registration", category: "Agriculture", org: "Ministry of Agriculture" }, kk: { name: "Шаруа қожалығын тіркеу", category: "Ауыл шаруашылығы", org: "Ауыл шаруашылығы министрлігі" }, keywords: ["fermer", "farm register", "dehqon", "сельхоз", "фермер", "farming", "agricultural registration", "qishloq xo'jaligi"] },
	{ id: 1402, uz: { name: "Qishloq xo'jaligi subsidiyasi olish", category: "Qishloq xo'jaligi", org: "Qishloq xo'jaligi vazirligi" }, ru: { name: "Получение сельскохозяйственной субсидии", category: "Сельское хозяйство", org: "Министерство сельского хозяйства" }, en: { name: "Agricultural Subsidy", category: "Agriculture", org: "Ministry of Agriculture" }, kk: { name: "Ауыл шаруашылығы субсидиясы алу", category: "Ауыл шаруашылығы", org: "Ауыл шаруашылығы министрлігі" }, keywords: ["qishloq subsidiya", "farm subsidy", "сельхоз субсидия", "agricultural grant", "urug' subsidiya", "fertilizer", "o'g'it"] },
	{ id: 1403, uz: { name: "Veterinariya sertifikati olish", category: "Qishloq xo'jaligi", org: "Veterinariya agentligi" }, ru: { name: "Получение ветеринарного сертификата", category: "Сельское хозяйство", org: "Ветеринарное агентство" }, en: { name: "Veterinary Certificate", category: "Agriculture", org: "Veterinary Agency" }, kk: { name: "Ветеринариялық куәлік алу", category: "Ауыл шаруашылығы", org: "Ветеринария агенттігі" }, keywords: ["veterinar", "hayvon", "mol", "livestock", "vet certificate", "ветеринар", "животное", "chorva", "qoramol", "qo'y", "echki", "chicken"] },
	{ id: 1404, uz: { name: "Sug'orish tizimi va kanal ishlarini ro'yxatga olish", category: "Qishloq xo'jaligi", org: "Suv xo'jaligi vazirligi" }, ru: { name: "Регистрация ирригационной системы и канала", category: "Сельское хозяйство", org: "Министерство водного хозяйства" }, en: { name: "Irrigation System and Canal Registration", category: "Agriculture", org: "Ministry of Water Resources" }, kk: { name: "Суару жүйесі мен арнаны тіркеу", category: "Ауыл шаруашылығы", org: "Су шаруашылығы министрлігі" }, keywords: ["sug'orish", "irrigation", "kanal", "ariq", "water farming", "каналы", "орошение", "farm water", "dala sug'orish"] },
	{ id: 1405, uz: { name: "O'g'it va pestitsidlarni sertifikatlashtirish", category: "Qishloq xo'jaligi", org: "Qishloq xo'jaligi vazirligi" }, ru: { name: "Сертификация удобрений и пестицидов", category: "Сельское хозяйство", org: "Министерство сельского хозяйства" }, en: { name: "Fertiliser and Pesticide Certification", category: "Agriculture", org: "Ministry of Agriculture" }, kk: { name: "Тыңайтқыш және пестицидтерді сертификаттау", category: "Ауыл шаруашылығы", org: "Ауыл шаруашылығы министрлігі" }, keywords: ["o'g'it", "pestitsid", "fertilizer", "pesticide", "chemical farm", "агрохимия", "agrochemical", "crop protection"] },
	{ id: 1406, uz: { name: "Qishloq xo'jaligi yerlarini ijaraga olish", category: "Qishloq xo'jaligi", org: "Yer resurslari agentligi" }, ru: { name: "Аренда сельскохозяйственных земель", category: "Сельское хозяйство", org: "Агентство земельных ресурсов" }, en: { name: "Agricultural Land Lease", category: "Agriculture", org: "Land Resources Agency" }, kk: { name: "Ауыл шаруашылығы жерлерін жалға алу", category: "Ауыл шаруашылығы", org: "Жер ресурстары агенттігі" }, keywords: ["qishloq yer ijara", "farm land lease", "agricultural land", "сельхоз земля", "yer ijarasi", "dala ijara", "dehqon yer"] },
	{ id: 1407, uz: { name: "Ekinlar eksportiga fitosanitariya sertifikati", category: "Qishloq xo'jaligi", org: "Karantin va o'simliklar muhofazasi agentligi" }, ru: { name: "Фитосанитарный сертификат на экспорт сельхозпродукции", category: "Сельское хозяйство", org: "Агентство карантина" }, en: { name: "Phytosanitary Certificate for Crop Export", category: "Agriculture", org: "Plant Quarantine Agency" }, kk: { name: "Өнімдерді экспортқа фитосанитариялық куәлік", category: "Ауыл шаруашылығы", org: "Карантин агенттігі" }, keywords: ["fitosanitariya", "phytosanitary", "plant export", "ekin eksport", "pomidor eksport", "fruit export", "vegetable export", "karantin"] },
];