export const JUSTICE_SERVICES = [
	{ id: 1101, uz: { name: "Notarial hujjatni tasdiqlash", category: "Huquq va sud", org: "Notariat" }, ru: { name: "Нотариальное удостоверение документа", category: "Право и суд", org: "Нотариат" }, en: { name: "Notarial Document Authentication", category: "Law and Courts", org: "Notariat" }, kk: { name: "Нотариалдық құжатты растау", category: "Құқық және сот", org: "Нотариат" }, keywords: ["notarius", "notarial", "нотариус", "нотариальный", "notarize", "hujjat tasdiqlash", "certify document", "legal document", "apostille"] },
	{ id: 1102, uz: { name: "Vasiyatnoma (vosiyatnoma) tuzish", category: "Huquq va sud", org: "Notariat" }, ru: { name: "Составление завещания", category: "Право и суд", org: "Нотариат" }, en: { name: "Will Preparation (Testament)", category: "Law and Courts", org: "Notariat" }, kk: { name: "Өсиет жазу", category: "Құқық және сот", org: "Нотариат" }, keywords: ["vasiyatnoma", "will", "testament", "завещание", "meros", "inheritance will", "vasiyat", "legal will"] },
	{ id: 1103, uz: { name: "Ishonchnoma (notarial) rasmiylashtirish", category: "Huquq va sud", org: "Notariat" }, ru: { name: "Нотариальное оформление доверенности", category: "Право и суд", org: "Нотариат" }, en: { name: "Power of Attorney (Notarised)", category: "Law and Courts", org: "Notariat" }, kk: { name: "Нотариалдық сенімхат рәсімдеу", category: "Құқық және сот", org: "Нотариат" }, keywords: ["ishonchnoma", "power of attorney", "доверенность", "notarial proxy", "notarize POA", "delegate authority", "wakalat"] },
	{ id: 1104, uz: { name: "Mulkni meros qilib olish rasmiylashtiruvi", category: "Huquq va sud", org: "Notariat" }, ru: { name: "Оформление наследства имущества", category: "Право и суд", org: "Нотариат" }, en: { name: "Property Inheritance Processing", category: "Law and Courts", org: "Notariat" }, kk: { name: "Мүліктік мұраны ресімдеу", category: "Құқық және сот", org: "Нотариат" }, keywords: ["meros", "inheritance", "наследство", "mulk meros", "ota mulki", "parent died property", "inherit", "meros olish", "heir"] },
	{ id: 1105, uz: { name: "Bepul huquqiy yordam olish", category: "Huquq va sud", org: "Adliya vazirligi" }, ru: { name: "Получение бесплатной юридической помощи", category: "Право и суд", org: "Министерство юстиции" }, en: { name: "Free Legal Aid", category: "Law and Courts", org: "Ministry of Justice" }, kk: { name: "Тегін заң көмегін алу", category: "Құқық және сот", org: "Әділет министрлігі" }, keywords: ["bepul huquq", "free legal aid", "бесплатная юридическая помощь", "free lawyer", "legal advice", "advokat", "attorney", "human rights"] },
	{ id: 1106, uz: { name: "Fuqarolik ishini sudga berish (da'vo)", category: "Huquq va sud", org: "Sudlar" }, ru: { name: "Подача гражданского иска в суд", category: "Право и суд", org: "Суды" }, en: { name: "Civil Court Claim Filing", category: "Law and Courts", org: "Courts" }, kk: { name: "Азаматтық талап сотқа беру", category: "Құқық және сот", org: "Соттар" }, keywords: ["sud", "da'vo", "court claim", "civil claim", "иск", "судебный", "sue", "lawsuit", "court case", "ariza sud"] },
	{ id: 1107, uz: { name: "Ma'muriy sudga ariza berish", category: "Huquq va sud", org: "Sudlar" }, ru: { name: "Подача заявления в административный суд", category: "Право и суд", org: "Суды" }, en: { name: "Administrative Court Application", category: "Law and Courts", org: "Courts" }, kk: { name: "Әкімшілік сотқа өтініш беру", category: "Құқық және сот", org: "Соттар" }, keywords: ["ma'muriy sud", "administrative court", "административный суд", "government action", "complaint court", "官 appeal"] },
	{ id: 1108, uz: { name: "Apellatsiya shikoyatini berish", category: "Huquq va sud", org: "Sudlar" }, ru: { name: "Подача апелляционной жалобы", category: "Право и суд", org: "Суды" }, en: { name: "Appeal Filing", category: "Law and Courts", org: "Courts" }, kk: { name: "Апелляциялық шағым беру", category: "Құқық және сот", org: "Соттар" }, keywords: ["apellatsiya", "appeal", "апелляция", "court appeal", "second instance", "qayta ko'rish", "review decision"] },
	{ id: 1109, uz: { name: "Advokat (huquqshunoslik) litsenziyasi olish", category: "Huquq va sud", org: "Adliya vazirligi" }, ru: { name: "Получение адвокатской лицензии", category: "Право и суд", org: "Министерство юстиции" }, en: { name: "Lawyer License (Bar Admission)", category: "Law and Courts", org: "Ministry of Justice" }, kk: { name: "Адвокат лицензиясын алу", category: "Құқық және сот", org: "Әділет министрлігі" }, keywords: ["advokat litsenziya", "lawyer license", "bar admission", "адвокатская лицензия", "law license", "attorney license", "bar exam"] },
	{ id: 1110, uz: { name: "Apostil qo'yish (xorijda hujjatni tan olish)", category: "Huquq va sud", org: "Adliya vazirligi" }, ru: { name: "Проставление апостиля (признание документа за рубежом)", category: "Право и суд", org: "Министерство юстиции" }, en: { name: "Apostille Stamp (International Document Recognition)", category: "Law and Courts", org: "Ministry of Justice" }, kk: { name: "Апостиль қою (шетелде құжатты тану)", category: "Құқық және сот", org: "Әділет министрлігі" }, keywords: ["apostil", "apostille", "hujjat tan olish", "document abroad", "xorijda hujjat", "international document", "legalize document", "notarial abroad"] },
	{ id: 1111, uz: { name: "Huquqiy tahlil va huquqiy ma'lumot olish", category: "Huquq va sud", org: "Adliya vazirligi" }, ru: { name: "Получение юридической консультации и информации", category: "Право и суд", org: "Министерство юстиции" }, en: { name: "Legal Consultation and Information", category: "Law and Courts", org: "Ministry of Justice" }, kk: { name: "Заң кеңесі мен ақпарат алу", category: "Құқық және сот", org: "Әділет министрлігі" }, keywords: ["huquqiy maslahat", "legal consultation", "юридическая консультация", "legal advice", "law info", "rights info", "legal question"] },
	{ id: 1112, uz: { name: "Mediatsiya (suddan tashqari kelishuv)", category: "Huquq va sud", org: "Adliya vazirligi" }, ru: { name: "Медиация (внесудебное урегулирование споров)", category: "Право и суд", org: "Министерство юстиции" }, en: { name: "Mediation (Out-of-court Dispute Resolution)", category: "Law and Courts", org: "Ministry of Justice" }, kk: { name: "Медиация (сотқа жүгінбей дауды шешу)", category: "Құқық және сот", org: "Әділет министрлігі" }, keywords: ["mediatsiya", "mediation", "dispute resolution", "out of court", "nizo hal", "kelishuv", "мировое соглашение", "arbitration"] },
];