export const PENSION_SERVICES = [
	{ id: 101, uz: { name: "Qariganligi bo'yicha pensiya tayinlash", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Назначение пенсии по старости", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Old-age Pension Assignment", category: "Pension", org: "Pension Fund" }, kk: { name: "Қарттық зейнетақы тағайындау", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["pensiya", "qariyalik", "old age", "pension", "zeynet", "пенсия", "старость", "retire", "nafaqa"] },
	{ id: 102, uz: { name: "Nogironlik bo'yicha pensiya tayinlash", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Назначение пенсии по инвалидности", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Disability Pension Assignment", category: "Pension", org: "Pension Fund" }, kk: { name: "Мүгедектік бойынша зейнетақы", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["nogironlik", "инвалидность", "disability pension", "мүгедек зейнетақы", "disabled pension"] },
	{ id: 103, uz: { name: "Boqimanda bo'yicha pensiya tayinlash", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Назначение пенсии по потере кормильца", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Survivor Pension (Loss of Breadwinner)", category: "Pension", org: "Pension Fund" }, kk: { name: "Асыраушыны жоғалтқан жағдайдағы зейнетақы", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["boqimanda", "loss breadwinner", "survivor pension", "потеря кормильца", "ota vafot nafaqa", "ona vafot nafaqa"] },
	{ id: 104, uz: { name: "18 yoshgacha nogironlarga nafaqa tayinlash", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Назначение пособия детям-инвалидам до 18 лет", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Disability Allowance for Children Under 18", category: "Pension", org: "Pension Fund" }, kk: { name: "18 жасқа дейінгі мүгедек балаларға жәрдемақы", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["nogiron bola", "child disability allowance", "детская инвалидность", "disabled child benefit"] },
	{ id: 105, uz: { name: "Parvarish nafaqasi olish", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Получение пособия по уходу", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Care Allowance", category: "Pension", org: "Pension Fund" }, kk: { name: "Күтім жәрдемақысы алу", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["parvarish", "care allowance", "уход", "пособие уход", "kasal parvarish", "elderly care"] },
	{ id: 106, uz: { name: "Bola tug'ilganda bir martalik nafaqa", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Единовременное пособие при рождении ребёнка", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "One-time Birth Allowance", category: "Pension", org: "Pension Fund" }, kk: { name: "Бала туғанда бір реттік жәрдемақы", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["bir martalik", "birth allowance", "единовременное", "рождение пособие", "bola tug'ildi pul", "newborn benefit"] },
	{ id: 107, uz: { name: "Dafn marosimi uchun bir martalik nafaqa", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Единовременное пособие на погребение", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Funeral Allowance", category: "Pension", org: "Pension Fund" }, kk: { name: "Жерлеу рәсіміне бір реттік жәрдемақы", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["dafn", "funeral allowance", "погребение", "пособие похороны", "o'lim nafaqa", "death benefit"] },
	{ id: 108, uz: { name: "Pensiya va nafaqa miqdori haqida ma'lumotnoma", category: "Pensiya", org: "Pensiya jamg'armasi" }, ru: { name: "Справка о размере пенсии и пособия", category: "Пенсия", org: "Пенсионный фонд" }, en: { name: "Certificate on Pension/Allowance Amount", category: "Pension", org: "Pension Fund" }, kk: { name: "Зейнетақы мөлшері туралы анықтама", category: "Зейнетақы", org: "Зейнетақы қоры" }, keywords: ["pensiya miqdori", "pension amount", "справка пенсия", "сумма пенсии", "pension certificate", "certificate pension"] },
	{ id: 109, uz: { name: "Kamligi tan olingan oilalarga yordam", category: "Ijtimoiy himoya", org: "Pensiya jamg'armasi" }, ru: { name: "Помощь семьям, признанным малоимущими", category: "Социальная защита", org: "Пенсионный фонд" }, en: { name: "Low-income Family Assistance", category: "Social Protection", org: "Pension Fund" }, kk: { name: "Кедей отбасыларға көмек", category: "Әлеуметтік қорғау", org: "Зейнетақы қоры" }, keywords: ["kam ta'minlangan", "low income", "малоимущий", "kambag'al oila", "poor family", "social assistance"] },
	{ id: 110, uz: { name: "HIV infektsiyasi bilan og'rigan 18 yoshgacha bolalarga nafaqa", category: "Ijtimoiy himoya", org: "Pensiya jamg'armasi" }, ru: { name: "Пособие детям до 18 лет с ВИЧ-инфекцией", category: "Социальная защита", org: "Пенсионный фонд" }, en: { name: "HIV Allowance for Children Under 18", category: "Social Protection", org: "Pension Fund" }, kk: { name: "ВИЧ-инфекциясы бар 18 жасқа дейінгі балаларға жәрдемақы", category: "Әлеуметтік қорғау", org: "Зейнетақы қоры" }, keywords: ["HIV", "СПИД", "AIDS", "child HIV", "bola HIV"] },
	{ id: 111, uz: { name: "Nogironligi bo'lgan onalarga yosh imtiyozi nafaqasi", category: "Ijtimoiy himoya", org: "Pensiya jamg'armasi" }, ru: { name: "Возрастная льгота матерям детей-инвалидов", category: "Социальная защита", org: "Пенсионный фонд" }, en: { name: "Age Benefit for Mothers of Disabled Children", category: "Social Protection", org: "Pension Fund" }, kk: { name: "Мүгедек балалары бар аналарға жас жеңілдігі", category: "Әлеуметтік қорғау", org: "Зейнетақы қоры" }, keywords: ["ona nogironlik", "disabled child mother", "мать инвалид", "mother disability benefit"] },
];