export const TAX_SERVICES = [
	{ id: 801, uz: { name: "Soliq deklaratsiyasini topshirish (jismoniy shaxslar)", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Подача налоговой декларации (физические лица)", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Tax Return Filing (Individuals)", category: "Taxes", org: "Tax Committee" }, kk: { name: "Салық декларациясын тапсыру (жеке тұлғалар)", category: "Салықтар", org: "Салық комитеті" }, keywords: ["deklaratsiya", "tax return", "физлица", "individual tax", "personal tax", "3-NDFL", "daromad solig'i", "income tax return"] },
	{ id: 802, uz: { name: "Soliq deklaratsiyasini topshirish (yuridik shaxslar)", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Подача налоговой декларации (юридические лица)", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Tax Return Filing (Legal Entities)", category: "Taxes", org: "Tax Committee" }, kk: { name: "Салық декларациясын тапсыру (заңды тұлғалар)", category: "Салықтар", org: "Салық комитеті" }, keywords: ["deklaratsiya yuridik", "corporate tax return", "налог юридическое", "company tax", "LLC tax", "korxona solig'i"] },
	{ id: 803, uz: { name: "STIR (soliq identifikatsiya raqami) olish", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Получение ИНН", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Tax Identification Number (TIN/STIR)", category: "Taxes", org: "Tax Committee" }, kk: { name: "СТТН (Салық төлеушінің тіркеу нөмірі) алу", category: "Салықтар", org: "Салық комитеті" }, keywords: ["STIR", "ИНН", "TIN", "tax number", "stir olish", "идентификационный номер", "fiscal number", "tax ID"] },
	{ id: 804, uz: { name: "Soliq qarzlari haqida ma'lumotnoma", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Справка об отсутствии налоговой задолженности", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Tax Clearance Certificate", category: "Taxes", org: "Tax Committee" }, kk: { name: "Салық қарызының жоқтығы туралы анықтама", category: "Салықтар", org: "Салық комитеті" }, keywords: ["soliq qarz", "tax clearance", "налоговая задолженность", "справка налог", "no tax debt", "soliqsiz ma'lumotnoma"] },
	{ id: 805, uz: { name: "QQS (Qo'shilgan qiymat solig'i) ro'yxatga olish", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Регистрация по НДС", category: "Налоги", org: "Налоговый комитет" }, en: { name: "VAT Registration", category: "Taxes", org: "Tax Committee" }, kk: { name: "ҚҚС тіркеуі", category: "Салықтар", org: "Салық комитеті" }, keywords: ["QQS", "NDS", "VAT", "ҚҚС", "НДС", "VAT register", "qo'shilgan qiymat", "value added tax"] },
	{ id: 806, uz: { name: "Mulk solig'ini to'lash", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Уплата налога на имущество", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Property Tax Payment", category: "Taxes", org: "Tax Committee" }, kk: { name: "Мүлік салығын төлеу", category: "Салықтар", org: "Салық комитеті" }, keywords: ["mulk solig'i", "property tax", "налог имущество", "uy solig'i", "house tax", "real estate tax"] },
	{ id: 807, uz: { name: "Transport solig'ini to'lash", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Уплата транспортного налога", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Vehicle Tax Payment", category: "Taxes", org: "Tax Committee" }, kk: { name: "Көлік салығын төлеу", category: "Салықтар", org: "Салық комитеті" }, keywords: ["transport solig'i", "vehicle tax", "транспортный налог", "mashina solig'i", "car tax"] },
	{ id: 808, uz: { name: "Yer solig'ini to'lash", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Уплата земельного налога", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Land Tax Payment", category: "Taxes", org: "Tax Committee" }, kk: { name: "Жер салығын төлеу", category: "Салықтар", org: "Салық комитеті" }, keywords: ["yer solig'i", "land tax", "земельный налог", "dacha tax", "yer to'lovi"] },
	{ id: 809, uz: { name: "Daromad solig'i imtiyozi (chegirmalar)", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Налоговый вычет по НДФЛ", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Income Tax Deduction", category: "Taxes", org: "Tax Committee" }, kk: { name: "ЖССН бойынша салықтық шегерім", category: "Салықтар", org: "Салық комитеті" }, keywords: ["chegirma", "daromad solig'i", "income tax deduction", "NDFL", "налоговый вычет", "tax refund", "вычет на детей", "property deduction"] },
	{ id: 810, uz: { name: "Soliq nazorati tekshiruvi uchun arizalar", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Заявления на налоговую проверку", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Tax Audit Application", category: "Taxes", org: "Tax Committee" }, kk: { name: "Салықтық тексеру туралы өтініштер", category: "Салықтар", org: "Салық комитеті" }, keywords: ["soliq tekshiruv", "tax audit", "налоговая проверка", "inspect", "audit", "soliq nazorat"] },
	{ id: 811, uz: { name: "Aksiz soliqlarini to'lash", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Уплата акцизного налога", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Excise Tax Payment", category: "Taxes", org: "Tax Committee" }, kk: { name: "Акциз салығын төлеу", category: "Салықтар", org: "Салық комитеті" }, keywords: ["aksiz", "excise", "акциз", "tobacco tax", "alcohol tax", "fuel tax", "spirtli ichimlik solig'i"] },
	{ id: 812, uz: { name: "Ijtimoiy soliqni to'lash (ish beruvchi uchun)", category: "Soliqlar", org: "Soliq qo'mitasi" }, ru: { name: "Уплата социального налога (для работодателей)", category: "Налоги", org: "Налоговый комитет" }, en: { name: "Social Tax Payment (for Employers)", category: "Taxes", org: "Tax Committee" }, kk: { name: "Әлеуметтік салықты төлеу (жұмыс берушілер үшін)", category: "Салықтар", org: "Салық комитеті" }, keywords: ["ijtimoiy soliq", "social tax", "социальный налог", "employer tax", "payroll tax", "ish beruvchi soliq"] },
];