export const UTILITY_SERVICES = [
	{ id: 1601, uz: { name: "Gaz ta'minotiga ulanish", category: "Kommunal xizmatlar", org: "O'zbekiston gazta'minoti" }, ru: { name: "Подключение к газоснабжению", category: "Коммунальные услуги", org: "Узгазснабжение" }, en: { name: "Gas Supply Connection", category: "Utilities", org: "Uzbekistan Gas Supply" }, kk: { name: "Газ жабдықтауына қосылу", category: "Коммуналдық қызметтер", org: "Өзбекстан газбен жабдықтау" }, keywords: ["gaz ulanish", "gas connection", "подключение газа", "gas supply", "gaz tortish", "new gas line", "gas meter"] },
	{ id: 1602, uz: { name: "Elektr energiyasiga ulanish", category: "Kommunal xizmatlar", org: "O'zbekenergo" }, ru: { name: "Подключение к электроснабжению", category: "Коммунальные услуги", org: "Узбекэнерго" }, en: { name: "Electricity Connection", category: "Utilities", org: "Uzbekenergo" }, kk: { name: "Электрмен жабдықтауға қосылу", category: "Коммуналдық қызметтер", org: "Өзбекэнерго" }, keywords: ["elektr ulanish", "electricity connection", "подключение электричества", "new electricity", "elektr tortish", "power connection"] },
	{ id: 1603, uz: { name: "Sovuq suv hisoblagichi o'rnatish va olib tashlash", category: "Kommunal xizmatlar", org: "Suvta'minot" }, ru: { name: "Установка и снятие счётчика холодной воды", category: "Коммунальные услуги", org: "Водоснабжение" }, en: { name: "Cold Water Meter Installation and Removal", category: "Utilities", org: "Water Supply" }, kk: { name: "Суық су есептегішін орнату және алу", category: "Коммуналдық қызметтер", org: "Сумен жабдықтау" }, keywords: ["suv hisoblagich", "water meter", "счётчик воды", "meter installation", "suv o'lchov", "install meter", "водомер"] },
	{ id: 1604, uz: { name: "Kommunal to'lovlarni onlayn to'lash", category: "Kommunal xizmatlar", org: "O'zinfotizim" }, ru: { name: "Онлайн оплата коммунальных услуг", category: "Коммунальные услуги", org: "Узинфотизим" }, en: { name: "Online Utility Bill Payment", category: "Utilities", org: "Uzinfotizim" }, kk: { name: "Коммуналдық қызметтерді онлайн төлеу", category: "Коммуналдық қызметтер", org: "Узинфотизим" }, keywords: ["kommunal to'lash", "utility payment", "оплата коммунальных", "online pay utilities", "bill pay", "hisob to'lash", "suv puli", "gaz puli"] },
	{ id: 1605, uz: { name: "Gaz hisoblagichi o'rnatish", category: "Kommunal xizmatlar", org: "O'zbekiston gazta'minoti" }, ru: { name: "Установка газового счётчика", category: "Коммунальные услуги", org: "Узгазснабжение" }, en: { name: "Gas Meter Installation", category: "Utilities", org: "Uzbekistan Gas Supply" }, kk: { name: "Газ есептегішін орнату", category: "Коммуналдық қызметтер", org: "Өзбекстан газбен жабдықтау" }, keywords: ["gaz hisoblagich", "gas meter", "газовый счётчик", "meter gas", "o'lchov gaz", "gas counter"] },
	{ id: 1606, uz: { name: "Elektr hisoblagichi o'rnatish yoki almashtirish", category: "Kommunal xizmatlar", org: "O'zbekenergo" }, ru: { name: "Установка или замена электросчётчика", category: "Коммунальные услуги", org: "Узбекэнерго" }, en: { name: "Electricity Meter Installation or Replacement", category: "Utilities", org: "Uzbekenergo" }, kk: { name: "Электр есептегішін орнату немесе ауыстыру", category: "Коммуналдық қызметтер", org: "Өзбекэнерго" }, keywords: ["elektr hisoblagich", "electricity meter", "электросчётчик", "meter replace", "elektr o'lchov", "meter installation electricity"] },
	{ id: 1607, uz: { name: "Markaziy isitish tizimiga ulanish", category: "Kommunal xizmatlar", org: "Issiqlik tarmoqlari" }, ru: { name: "Подключение к центральному отоплению", category: "Коммунальные услуги", org: "Теплосети" }, en: { name: "Central Heating Connection", category: "Utilities", org: "Heat Networks" }, kk: { name: "Орталық жылыту жүйесіне қосылу", category: "Коммуналдық қызметтер", org: "Жылу желілері" }, keywords: ["isitish", "heating", "отопление", "central heating", "qozon", "qazan", "winter heating", "uy isitish", "connect heating"] },
	{ id: 1608, uz: { name: "Oqova suv tizimiga ulanish (kanalizatsiya)", category: "Kommunal xizmatlar", org: "Suvta'minot" }, ru: { name: "Подключение к канализации", category: "Коммунальные услуги", org: "Водоснабжение" }, en: { name: "Sewage/Sewerage Connection", category: "Utilities", org: "Water Supply" }, kk: { name: "Кәрізге қосылу", category: "Коммуналдық қызметтер", org: "Сумен жабдықтау" }, keywords: ["kanalizatsiya", "sewage", "канализация", "oqova suv", "sewerage connection", "drainage", "waste water"] },
	{ id: 1609, uz: { name: "Kommunal xizmatlar shikoyatini ko'rib chiqish", category: "Kommunal xizmatlar", org: "Antimonopol qo'mita" }, ru: { name: "Рассмотрение жалоб на коммунальные услуги", category: "Коммунальные услуги", org: "Антимонопольный комитет" }, en: { name: "Utility Service Complaint Review", category: "Utilities", org: "Anti-Monopoly Committee" }, kk: { name: "Коммуналдық қызметтерге шағымды қарастыру", category: "Коммуналдық қызметтер", org: "Монополияға қарсы комитет" }, keywords: ["kommunal shikoyat", "utility complaint", "жалоба коммунальный", "gaz problem", "water problem", "power outage", "suv muammo", "electricity issue"] },
	{ id: 1610, uz: { name: "Internet va telefon xizmatlariga ulanish", category: "Kommunal xizmatlar", org: "Axborot texnologiyalari vazirligi" }, ru: { name: "Подключение к интернету и телефонным услугам", category: "Коммунальные услуги", org: "Министерство ИТ" }, en: { name: "Internet and Telephone Service Connection", category: "Utilities", org: "Ministry of IT" }, kk: { name: "Интернет пен телефон қызметтеріне қосылу", category: "Коммуналдық қызметтер", org: "АТ министрлігі" }, keywords: ["internet", "telefon", "telephone", "connect internet", "ISP", "broadband", "fiber", "ADSL", "internet ulanish", "phone line"] },
];